<Project Sdk="Microsoft.NET.Sdk.Razor">
	<PropertyGroup>
		<TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
		<Nullable>enable</Nullable>
		<AddRazorSupportForMvc>true</AddRazorSupportForMvc>

		<PackageId>RazorForms</PackageId>
		<Title>RazorForms</Title>
		<PackageVersion>2.0.0</PackageVersion>
		<PackageReleaseNotes>
			Minor bug fixes
		</PackageReleaseNotes>
		<Authors>Christian LeVesque</Authors>
		<Description>A small, configurable library of form tag helpers for Razor Pages. The goal of RazorForms is to create a package that can support most popular front-end CSS frameworks, or be configured to support your own custom CSS.</Description>
		<Copyright>Copyright Christian LeVesque 2022</Copyright>
		<PackageProjectUrl>https://www.razorforms.com</PackageProjectUrl>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<RepositoryUrl>https://github.com/christianlevesque/RazorForms</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageTags>razor page form ui component</PackageTags>
		<PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
	</PropertyGroup>

	<ItemGroup>
		<None Include="../README.md" Pack="true" PackagePath="/" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net8.0' or '$(TargetFramework)' == 'net9.0' or '$(TargetFramework)' == 'net10.0'">
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>
</Project>
